# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty
#relative_permalinks: true

# Setup
title:            Simbiosis
tagline:          'Evento de exploración multidisciplinar de la realidad'
description:      'Evento de creación y experimentación multidisciplinar'
url:              http://www.simbiosis.github.io
baseurl:          ''

author:
  name:           'Simbiotes'
  url:            https://twitter.com/simbiosis

#paginate:         5

# Custom vars
version:          1.0

github:
  repo:           https://github.com/simbiosis
